// Database types for Supabase
// This file would typically be auto-generated by Supabase CLI

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          phone_number: string | null
          preferred_language: 'en' | 'fr'
          role: 'super_admin' | 'restaurant_manager' | 'kitchen_staff' | 'club_manager' | 'bouncer' | 'customer'
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          phone_number?: string | null
          preferred_language?: 'en' | 'fr'
          role?: 'super_admin' | 'restaurant_manager' | 'kitchen_staff' | 'club_manager' | 'bouncer' | 'customer'
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          phone_number?: string | null
          preferred_language?: 'en' | 'fr'
          role?: 'super_admin' | 'restaurant_manager' | 'kitchen_staff' | 'club_manager' | 'bouncer' | 'customer'
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      business_settings: {
        Row: {
          id: string
          business_name: string
          restaurant_name: string
          club_name: string
          timezone: string
          restaurant_opens_at: string
          restaurant_closes_at: string
          restaurant_order_override: boolean
          restaurant_order_override_reason: string | null
          club_opens_at: string
          club_closes_at: string
          address: string
          coordinates: string | null
          phone: string
          email: string
          whatsapp: string | null
          default_currency: string
          payment_provider: 'campay' | 'monetbil' | 'sandbox'
          cancellation_policy: string
          social_links: Json
          map_url: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_name: string
          restaurant_name: string
          club_name: string
          timezone?: string
          restaurant_opens_at: string
          restaurant_closes_at: string
          restaurant_order_override?: boolean
          restaurant_order_override_reason?: string | null
          club_opens_at: string
          club_closes_at: string
          address: string
          coordinates?: string | null
          phone: string
          email: string
          whatsapp?: string | null
          default_currency?: string
          payment_provider?: 'campay' | 'monetbil' | 'sandbox'
          cancellation_policy?: string
          social_links?: Json
          map_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_name?: string
          restaurant_name?: string
          club_name?: string
          timezone?: string
          restaurant_opens_at?: string
          restaurant_closes_at?: string
          restaurant_order_override?: boolean
          restaurant_order_override_reason?: string | null
          club_opens_at?: string
          club_closes_at?: string
          address?: string
          coordinates?: string | null
          phone?: string
          email?: string
          whatsapp?: string | null
          default_currency?: string
          payment_provider?: 'campay' | 'monetbil' | 'sandbox'
          cancellation_policy?: string
          social_links?: Json
          map_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      restaurant_categories: {
        Row: {
          id: string
          name_en: string
          name_fr: string
          slug: string
          description_en: string | null
          description_fr: string | null
          display_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name_en: string
          name_fr: string
          slug: string
          description_en?: string | null
          description_fr?: string | null
          display_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name_en?: string
          name_fr?: string
          slug?: string
          description_en?: string | null
          description_fr?: string | null
          display_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      menu_items: {
        Row: {
          id: string
          category_id: string
          name_en: string
          name_fr: string
          description_en: string | null
          description_fr: string | null
          price_xaf: number
          preparation_time_minutes: number
          image_path: string | null
          is_available: boolean
          late_night_available: boolean
          is_featured: boolean
          display_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          category_id: string
          name_en: string
          name_fr: string
          description_en?: string | null
          description_fr?: string | null
          price_xaf: number
          preparation_time_minutes?: number
          image_path?: string | null
          is_available?: boolean
          late_night_available?: boolean
          is_featured?: boolean
          display_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          category_id?: string
          name_en?: string
          name_fr?: string
          description_en?: string | null
          description_fr?: string | null
          price_xaf?: number
          preparation_time_minutes?: number
          image_path?: string | null
          is_available?: boolean
          late_night_available?: boolean
          is_featured?: boolean
          display_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      physical_tables: {
        Row: {
          id: string
          table_code: string
          display_name: string
          table_type: 'restaurant_standard' | 'club_regular' | 'club_vip' | 'club_vvip'
          section: string
          capacity: number
          minimum_spend_xaf: number
          map_x: number
          map_y: number
          width: number
          height: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          table_code: string
          display_name: string
          table_type: 'restaurant_standard' | 'club_regular' | 'club_vip' | 'club_vvip'
          section: string
          capacity: number
          minimum_spend_xaf?: number
          map_x: number
          map_y: number
          width?: number
          height?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          table_code?: string
          display_name?: string
          table_type?: 'restaurant_standard' | 'club_regular' | 'club_vip' | 'club_vvip'
          section?: string
          capacity?: number
          minimum_spend_xaf?: number
          map_x?: number
          map_y?: number
          width?: number
          height?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      orders: {
        Row: {
          id: string
          user_id: string
          delivery_type: 'dine_in' | 'takeaway'
          restaurant_table_id: string | null
          status: 'draft' | 'pending_payment' | 'paid' | 'preparing' | 'ready' | 'completed' | 'cancelled' | 'refunded'
          subtotal_xaf: number
          fees_xaf: number
          total_xaf: number
          customer_note: string | null
          kitchen_note: string | null
          payment_status: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          created_at: string
          paid_at: string | null
          preparing_at: string | null
          ready_at: string | null
          completed_at: string | null
          cancelled_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          delivery_type: 'dine_in' | 'takeaway'
          restaurant_table_id?: string | null
          status?: 'draft' | 'pending_payment' | 'paid' | 'preparing' | 'ready' | 'completed' | 'cancelled' | 'refunded'
          subtotal_xaf?: number
          fees_xaf?: number
          total_xaf?: number
          customer_note?: string | null
          kitchen_note?: string | null
          payment_status?: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          created_at?: string
          paid_at?: string | null
          preparing_at?: string | null
          ready_at?: string | null
          completed_at?: string | null
          cancelled_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          delivery_type?: 'dine_in' | 'takeaway'
          restaurant_table_id?: string | null
          status?: 'draft' | 'pending_payment' | 'paid' | 'preparing' | 'ready' | 'completed' | 'cancelled' | 'refunded'
          subtotal_xaf?: number
          fees_xaf?: number
          total_xaf?: number
          customer_note?: string | null
          kitchen_note?: string | null
          payment_status?: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          created_at?: string
          paid_at?: string | null
          preparing_at?: string | null
          ready_at?: string | null
          completed_at?: string | null
          cancelled_at?: string | null
        }
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          menu_item_id: string
          item_name_snapshot: string
          unit_price_snapshot: number
          quantity: number
          line_total_xaf: number
          customer_instructions: string | null
          created_at: string
        }
        Insert: {
          id?: string
          order_id: string
          menu_item_id: string
          item_name_snapshot: string
          unit_price_snapshot: number
          quantity: number
          line_total_xaf?: number
          customer_instructions?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          menu_item_id?: string
          item_name_snapshot?: string
          unit_price_snapshot?: number
          quantity?: number
          line_total_xaf?: number
          customer_instructions?: string | null
          created_at?: string
        }
      }
      events: {
        Row: {
          id: string
          title_en: string
          title_fr: string
          slug: string
          description_en: string | null
          description_fr: string | null
          start_at: string
          end_at: string
          doors_open_at: string
          flyer_path: string | null
          venue: string
          is_published: boolean
          is_featured: boolean
          age_policy: string | null
          dress_code: string | null
          is_cancelled: boolean
          cancellation_reason: string | null
          seo_title_en: string | null
          seo_title_fr: string | null
          seo_description_en: string | null
          seo_description_fr: string | null
          notification_sent: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title_en: string
          title_fr: string
          slug: string
          description_en?: string | null
          description_fr?: string | null
          start_at: string
          end_at: string
          doors_open_at?: string
          flyer_path?: string | null
          venue?: string
          is_published?: boolean
          is_featured?: boolean
          age_policy?: string | null
          dress_code?: string | null
          is_cancelled?: boolean
          cancellation_reason?: string | null
          seo_title_en?: string | null
          seo_title_fr?: string | null
          seo_description_en?: string | null
          seo_description_fr?: string | null
          notification_sent?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title_en?: string
          title_fr?: string
          slug?: string
          description_en?: string | null
          description_fr?: string | null
          start_at?: string
          end_at?: string
          doors_open_at?: string
          flyer_path?: string | null
          venue?: string
          is_published?: boolean
          is_featured?: boolean
          age_policy?: string | null
          dress_code?: string | null
          is_cancelled?: boolean
          cancellation_reason?: string | null
          seo_title_en?: string | null
          seo_title_fr?: string | null
          seo_description_en?: string | null
          seo_description_fr?: string | null
          notification_sent?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      ticket_types: {
        Row: {
          id: string
          event_id: string
          name_en: string
          name_fr: string
          description_en: string | null
          description_fr: string | null
          price_xaf: number
          total_inventory: number
          reserved_inventory: number
          sold_inventory: number
          sales_start_at: string
          sales_end_at: string
          max_per_purchase: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          event_id: string
          name_en: string
          name_fr: string
          description_en?: string | null
          description_fr?: string | null
          price_xaf: number
          total_inventory: number
          reserved_inventory?: number
          sold_inventory?: number
          sales_start_at: string
          sales_end_at: string
          max_per_purchase?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          name_en?: string
          name_fr?: string
          description_en?: string | null
          description_fr?: string | null
          price_xaf?: number
          total_inventory?: number
          reserved_inventory?: number
          sold_inventory?: number
          sales_start_at?: string
          sales_end_at?: string
          max_per_purchase?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      event_tables: {
        Row: {
          id: string
          event_id: string
          physical_table_id: string
          price_xaf: number
          minimum_spend_xaf: number
          status: 'available' | 'locked' | 'reserved' | 'occupied' | 'unavailable'
          locked_by_user_id: string | null
          locked_until: string | null
          reservation_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          event_id: string
          physical_table_id: string
          price_xaf?: number
          minimum_spend_xaf?: number
          status?: 'available' | 'locked' | 'reserved' | 'occupied' | 'unavailable'
          locked_by_user_id?: string | null
          locked_until?: string | null
          reservation_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          physical_table_id?: string
          price_xaf?: number
          minimum_spend_xaf?: number
          status?: 'available' | 'locked' | 'reserved' | 'occupied' | 'unavailable'
          locked_by_user_id?: string | null
          locked_until?: string | null
          reservation_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      reservations: {
        Row: {
          id: string
          user_id: string
          event_id: string
          event_table_id: string | null
          guest_count: number
          status: 'pending_payment' | 'confirmed' | 'checked_in' | 'cancelled' | 'expired' | 'refunded'
          deposit_amount_xaf: number
          total_amount_xaf: number
          payment_status: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          customer_note: string | null
          confirmed_at: string | null
          checked_in_at: string | null
          cancelled_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          event_id: string
          event_table_id?: string | null
          guest_count?: number
          status?: 'pending_payment' | 'confirmed' | 'checked_in' | 'cancelled' | 'expired' | 'refunded'
          deposit_amount_xaf?: number
          total_amount_xaf?: number
          payment_status?: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          customer_note?: string | null
          confirmed_at?: string | null
          checked_in_at?: string | null
          cancelled_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          event_id?: string
          event_table_id?: string | null
          guest_count?: number
          status?: 'pending_payment' | 'confirmed' | 'checked_in' | 'cancelled' | 'expired' | 'refunded'
          deposit_amount_xaf?: number
          total_amount_xaf?: number
          payment_status?: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          customer_note?: string | null
          confirmed_at?: string | null
          checked_in_at?: string | null
          cancelled_at?: string | null
          created_at?: string
        }
      }
      event_ticket_orders: {
        Row: {
          id: string
          user_id: string
          event_id: string
          status: 'draft' | 'pending_payment' | 'paid' | 'completed' | 'cancelled' | 'refunded'
          subtotal_xaf: number
          fees_xaf: number
          total_xaf: number
          payment_status: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          created_at: string
          paid_at: string | null
          cancelled_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          event_id: string
          status?: 'draft' | 'pending_payment' | 'paid' | 'completed' | 'cancelled' | 'refunded'
          subtotal_xaf?: number
          fees_xaf?: number
          total_xaf?: number
          payment_status?: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          created_at?: string
          paid_at?: string | null
          cancelled_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          event_id?: string
          status?: 'draft' | 'pending_payment' | 'paid' | 'completed' | 'cancelled' | 'refunded'
          subtotal_xaf?: number
          fees_xaf?: number
          total_xaf?: number
          payment_status?: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          created_at?: string
          paid_at?: string | null
          cancelled_at?: string | null
        }
      }
      event_ticket_items: {
        Row: {
          id: string
          ticket_order_id: string
          ticket_type_id: string
          ticket_name_snapshot: string
          unit_price_snapshot: number
          quantity: number
          line_total_xaf: number
          created_at: string
        }
        Insert: {
          id?: string
          ticket_order_id: string
          ticket_type_id: string
          ticket_name_snapshot: string
          unit_price_snapshot: number
          quantity: number
          line_total_xaf?: number
          created_at?: string
        }
        Update: {
          id?: string
          ticket_order_id?: string
          ticket_type_id?: string
          ticket_name_snapshot?: string
          unit_price_snapshot?: number
          quantity?: number
          line_total_xaf?: number
          created_at?: string
        }
      }
      guest_list_entries: {
        Row: {
          id: string
          event_id: string
          user_id: string | null
          guest_name: string | null
          guest_phone: string | null
          guest_email: string | null
          guest_count: number
          status: 'pending' | 'approved' | 'rejected' | 'checked_in' | 'cancelled'
          approved_by: string | null
          approved_at: string | null
          rejection_reason: string | null
          checked_in_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          user_id?: string | null
          guest_name?: string | null
          guest_phone?: string | null
          guest_email?: string | null
          guest_count?: number
          status?: 'pending' | 'approved' | 'rejected' | 'checked_in' | 'cancelled'
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          checked_in_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          user_id?: string | null
          guest_name?: string | null
          guest_phone?: string | null
          guest_email?: string | null
          guest_count?: number
          status?: 'pending' | 'approved' | 'rejected' | 'checked_in' | 'cancelled'
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          checked_in_at?: string | null
          created_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          user_id: string
          provider: 'campay' | 'monetbil' | 'sandbox'
          internal_reference: string
          provider_reference: string | null
          target_type: 'order' | 'reservation' | 'ticket_order'
          target_id: string
          payment_method: string | null
          phone_number: string | null
          amount_xaf: number
          currency: string
          status: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          failure_code: string | null
          failure_message: string | null
          initiated_at: string
          confirmed_at: string | null
          failed_at: string | null
          refunded_at: string | null
          idempotency_key: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          provider: 'campay' | 'monetbil' | 'sandbox'
          internal_reference: string
          provider_reference?: string | null
          target_type: 'order' | 'reservation' | 'ticket_order'
          target_id: string
          payment_method?: string | null
          phone_number?: string | null
          amount_xaf: number
          currency?: string
          status?: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          failure_code?: string | null
          failure_message?: string | null
          initiated_at?: string
          confirmed_at?: string | null
          failed_at?: string | null
          refunded_at?: string | null
          idempotency_key: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          provider?: 'campay' | 'monetbil' | 'sandbox'
          internal_reference?: string
          provider_reference?: string | null
          target_type?: 'order' | 'reservation' | 'ticket_order'
          target_id?: string
          payment_method?: string | null
          phone_number?: string | null
          amount_xaf?: number
          currency?: string
          status?: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
          failure_code?: string | null
          failure_message?: string | null
          initiated_at?: string
          confirmed_at?: string | null
          failed_at?: string | null
          refunded_at?: string | null
          idempotency_key?: string
          created_at?: string
        }
      }
      payment_events: {
        Row: {
          id: string
          provider: string
          provider_event_id: string
          payment_reference: string | null
          event_type: string
          signature_valid: boolean
          sanitized_payload: Json
          processing_status: 'received' | 'processing' | 'processed' | 'failed'
          received_at: string
          processed_at: string | null
          processing_error: string | null
        }
        Insert: {
          id?: string
          provider: string
          provider_event_id: string
          payment_reference?: string | null
          event_type: string
          signature_valid?: boolean
          sanitized_payload?: Json
          processing_status?: 'received' | 'processing' | 'processed' | 'failed'
          received_at?: string
          processed_at?: string | null
          processing_error?: string | null
        }
        Update: {
          id?: string
          provider?: string
          provider_event_id?: string
          payment_reference?: string | null
          event_type?: string
          signature_valid?: boolean
          sanitized_payload?: Json
          processing_status?: 'received' | 'processing' | 'processed' | 'failed'
          received_at?: string
          processed_at?: string | null
          processing_error?: string | null
        }
      }
      passes: {
        Row: {
          id: string
          user_id: string
          event_id: string
          target_type: 'order' | 'reservation' | 'ticket_order'
          target_id: string
          token_hash: string
          token_version: number
          status: 'active' | 'checked_in' | 'cancelled' | 'expired' | 'revoked'
          issued_at: string
          expires_at: string
          checked_in_at: string | null
          checked_in_by: string | null
          revoked_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          event_id: string
          target_type: 'order' | 'reservation' | 'ticket_order'
          target_id: string
          token_hash: string
          token_version?: number
          status?: 'active' | 'checked_in' | 'cancelled' | 'expired' | 'revoked'
          issued_at?: string
          expires_at: string
          checked_in_at?: string | null
          checked_in_by?: string | null
          revoked_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          event_id?: string
          target_type?: 'order' | 'reservation' | 'ticket_order'
          target_id?: string
          token_hash?: string
          token_version?: number
          status?: 'active' | 'checked_in' | 'cancelled' | 'expired' | 'revoked'
          issued_at?: string
          expires_at?: string
          checked_in_at?: string | null
          checked_in_by?: string | null
          revoked_at?: string | null
          created_at?: string
        }
      }
      push_subscriptions: {
        Row: {
          id: string
          user_id: string | null
          endpoint: string
          keys_p256dh: string
          keys_auth: string
          locale: 'en' | 'fr'
          user_agent: string | null
          is_active: boolean
          last_success_at: string | null
          failure_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          endpoint: string
          keys_p256dh: string
          keys_auth: string
          locale?: 'en' | 'fr'
          user_agent?: string | null
          is_active?: boolean
          last_success_at?: string | null
          failure_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          endpoint?: string
          keys_p256dh?: string
          keys_auth?: string
          locale?: 'en' | 'fr'
          user_agent?: string | null
          is_active?: boolean
          last_success_at?: string | null
          failure_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string | null
          title_en: string
          title_fr: string
          body_en: string
          body_fr: string
          data: Json
          sent_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          title_en: string
          title_fr: string
          body_en: string
          body_fr: string
          data?: Json
          sent_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          title_en?: string
          title_fr?: string
          body_en?: string
          body_fr?: string
          data?: Json
          sent_at?: string | null
          created_at?: string
        }
      }
      audit_logs: {
        Row: {
          id: string
          actor_id: string | null
          actor_role: 'super_admin' | 'restaurant_manager' | 'kitchen_staff' | 'club_manager' | 'bouncer' | 'customer' | null
          action: string
          entity_type: string
          entity_id: string | null
          before_state: Json | null
          after_state: Json | null
          request_id: string | null
          ip_hash: string | null
          created_at: string
        }
        Insert: {
          id?: string
          actor_id?: string | null
          actor_role?: 'super_admin' | 'restaurant_manager' | 'kitchen_staff' | 'club_manager' | 'bouncer' | 'customer' | null
          action: string
          entity_type: string
          entity_id?: string | null
          before_state?: Json | null
          after_state?: Json | null
          request_id?: string | null
          ip_hash?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          actor_id?: string | null
          actor_role?: 'super_admin' | 'restaurant_manager' | 'kitchen_staff' | 'club_manager' | 'bouncer' | 'customer' | null
          action?: string
          entity_type?: string
          entity_id?: string | null
          before_state?: Json | null
          after_state?: Json | null
          request_id?: string | null
          ip_hash?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'super_admin' | 'restaurant_manager' | 'kitchen_staff' | 'club_manager' | 'bouncer' | 'customer'
      locale: 'en' | 'fr'
      order_type: 'dine_in' | 'takeaway'
      order_status: 'draft' | 'pending_payment' | 'paid' | 'preparing' | 'ready' | 'completed' | 'cancelled' | 'refunded'
      payment_status: 'initiated' | 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded' | 'partially_refunded'
      payment_provider: 'campay' | 'monetbil' | 'sandbox'
      reservation_status: 'pending_payment' | 'confirmed' | 'checked_in' | 'cancelled' | 'expired' | 'refunded'
      pass_status: 'active' | 'checked_in' | 'cancelled' | 'expired' | 'revoked'
      event_table_status: 'available' | 'locked' | 'reserved' | 'occupied' | 'unavailable'
      guest_list_status: 'pending' | 'approved' | 'rejected' | 'checked_in' | 'cancelled'
      table_type: 'restaurant_standard' | 'club_regular' | 'club_vip' | 'club_vvip'
      package_category: 'drinks' | 'champagne' | 'bottles' | 'vip_gold' | 'custom'
      package_status: 'active' | 'inactive' | 'sold_out'
    }
  }
}

// Additional types for club packages and delivery
export type PackageCategory = 'drinks' | 'champagne' | 'bottles' | 'vip_gold' | 'custom';
export type PackageStatus = 'active' | 'inactive' | 'sold_out';

export interface ClubPackage {
  id: string;
  name_en: string;
  name_fr: string;
  description_en: string | null;
  description_fr: string | null;
  category: PackageCategory;
  includes_en: string | null;
  includes_fr: string | null;
  price_xaf: number;
  deposit_xaf: number;
  minimum_spend_xaf: number;
  capacity: number;
  max_per_event: number | null;
  inventory: number | null;
  reserved: number;
  sold: number;
  is_vip: boolean;
  is_featured: boolean;
  display_order: number;
  sales_start_at: string | null;
  sales_end_at: string | null;
  status: PackageStatus;
  created_at: string;
  updated_at: string;
}

export interface EventPackageAvailability {
  id: string;
  event_id: string;
  package_id: string;
  custom_price_xaf: number | null;
  custom_deposit_xaf: number | null;
  available_inventory: number | null;
  is_available: boolean;
  created_at: string;
}

export interface ReservationPackage {
  id: string;
  reservation_id: string;
  package_id: string;
  quantity: number;
  unit_price_snapshot: number;
  line_total_snapshot: number;
  created_at: string;
}

export interface DeliveryZone {
  id: string;
  name_en: string;
  name_fr: string;
  description_en: string | null;
  description_fr: string | null;
  delivery_fee_xaf: number;
  min_order_xaf: number;
  estimated_minutes: number;
  estimated_max_minutes: number;
  is_active: boolean;
  display_order: number;
  created_at: string;
  updated_at: string;
}

export interface DeliveryAddress {
  address: string;
  landmark?: string;
  coordinates?: string;
  instructions?: string;
  zone_id?: string;
}
